repos:
  - repo: https://github.com/johnnymorganz/stylua
    rev: v2.0.2
    hooks:
      - id: stylua-github
        fail_fast: true
        verbose: true
        types: [lua]
  - repo: local
    hooks:
      - id: luacheck
        name: Luacheck
        description: Lints Lua files using Luacheck.
        entry: luacheck --
        language: system
        fail_fast: true
        verbose: true
        types: [lua]
